import os
import logging
import base64
import json
import time
import requests
from io import BytesIO
from flask import Flask, request, jsonify, render_template
from PIL import Image
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Initialize Flask app
app = Flask(__name__, template_folder='templates')

# Metrics
INFER_COUNT = Counter("infer_requests_total", "Total inference requests")
INFER_LATENCY = Histogram("infer_latency_seconds", "Inference latency")

@app.route("/metrics")
def metrics():
    """Prometheus metrics endpoint"""
    return generate_latest(), 200, {"Content-Type": CONTENT_TYPE_LATEST}

@app.before_request
def before_request():
    """Store request start time for latency calculation"""
    request.start_time = time.time()

@app.after_request
def after_request(response):
    """Record metrics after request is processed"""
    if request.endpoint == "infer":
        INFER_COUNT.inc()
        if hasattr(request, 'start_time'):
            INFER_LATENCY.observe(time.time() - request.start_time)
    return response

# Mock class to simulate the BLIP model for demonstration purposes
class MockBLIPModel:
    def __init__(self):
        self.config = type('obj', (object,), {
            '_name_or_path': 'Salesforce/blip-image-captioning-base (mock)'
        })
    
    def generate(self, **kwargs):
        # Simulate model generation
        return [0]  # Return a mock token ID
    
    def to(self, device):
        # Mock method to simulate moving model to device
        logger.info(f"Mock: Moving model to {device}")
        return self

# Mock class to simulate the BLIP processor
class MockBLIPProcessor:
    @staticmethod
    def from_pretrained(model_name):
        logger.info(f"Mock: Loading processor from {model_name}")
        return MockBLIPProcessor()
    
    def __call__(self, image, return_tensors="pt"):
        # Simulate processing an image
        logger.info(f"Mock: Processing image to {return_tensors} tensors")
        return type('obj', (object,), {'to': lambda device: {'input_ids': None}})
    
    def decode(self, token_ids, skip_special_tokens=True):
        # Simulate decoding token IDs to text
        return "This is a mock image caption generated by the API."

# Initialize mock processor and model
processor = MockBLIPProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = MockBLIPModel().to("cuda")

@app.route('/', methods=['GET'])
def home():
    """Homepage with information about the API"""
    # Return an HTML template for better user experience
    return render_template('index.html', 
                          version="1.0.0", 
                          status="running")

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint for Kubernetes liveness and readiness probes"""
    return jsonify({"status": "healthy"}), 200

def decode_image(image_data):
    """
    Decode an image from a URL or base64 string.
    
    Args:
        image_data (str): A URL or base64-encoded image
        
    Returns:
        PIL.Image: The decoded image
    """
    try:
        # Check if the image data is a URL
        if image_data.startswith(('http://', 'https://')):
            logger.info("Downloading image from URL")
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
            response = requests.get(image_data, headers=headers)
            response.raise_for_status()  # Raise an error for bad status codes
            image = Image.open(BytesIO(response.content))
            return image
        
        # Otherwise, assume it's a base64-encoded string
        else:
            logger.info("Decoding base64 image")
            # Remove the data URL prefix if present
            if ',' in image_data:
                image_data = image_data.split(',')[1]
                
            # Decode base64 string
            image_bytes = base64.b64decode(image_data)
            image = Image.open(BytesIO(image_bytes))
            return image
            
    except Exception as e:
        logger.error(f"Error decoding image: {str(e)}")
        raise ValueError(f"Failed to decode image: {str(e)}")

@app.route('/infer', methods=['POST'])
def infer():
    """
    Model inference endpoint. Accepts JSON input for image captioning.
    
    Example payload:
    {
        "image": "base64-encoded image or image URL"
    }
    
    Returns:
    {
        "predictions": "image caption result",
        "model_version": "version of the model used"
    }
    """
    try:
        # Get JSON data from request
        request_data = request.get_json()
        
        if not request_data:
            return jsonify({"error": "No input data provided"}), 400
        
        image_data = request_data.get('image')
        if not image_data:
            return jsonify({"error": "Missing 'image' field in request"}), 400
        
        # Log the inference request (truncate large payloads)
        if len(image_data) > 100:
            log_data = image_data[:50] + "..." + image_data[-50:]
        else:
            log_data = image_data
            
        logger.info(f"Received inference request with image data: {log_data}")
        
        # Process the image
        try:
            image = decode_image(image_data)
            logger.info(f"Image decoded successfully: {image.size}")
            
            # Process with BLIP model
            inputs = processor(image, return_tensors="pt").to("cuda")
            output_ids = model.generate(**inputs)
            caption = processor.decode(output_ids[0], skip_special_tokens=True)
            
            # Return the results
            result = {
                "predictions": caption,
                "model_version": model.config._name_or_path
            }
            
            logger.info("Inference completed successfully")
            return jsonify(result), 200
            
        except ValueError as ve:
            return jsonify({"error": str(ve)}), 400
    
    except Exception as e:
        logger.error(f"Error during inference: {str(e)}")
        return jsonify({"error": f"Error processing request: {str(e)}"}), 500

if __name__ == '__main__':
    # Get port from environment variable or use default
    port = int(os.environ.get('PORT', 5000))
    
    # Log server startup
    logger.info(f"Starting model server on port {port}")
    
    # Run the Flask app
    app.run(host='0.0.0.0', port=port, debug=False)